### PR TITLE
fix bug when calculating angles from faces

### PR DESCRIPTION
**Pull request by bertjiazheng**
Correct me if I am wrong.

### CODE REVIEW

**Comment by bertjiazheng** [comment]
Hi @ranahanocka,

I make this PR more clear. 

The function [angles_from_faces](https://github.com/ranahanocka/MeshCNN/blob/master/models/layers/mesh_prepare.py#L209) computes the dihedral angle between the two faces:
1. select two edges from the same face
2. compute normal by the cross product of two edges
3. obtain the dihedral angle by the inner product of the two normals.

However, when computing the normals of two faces _normals_ in step 1, the _edge_a_ and _edge_b_ are from two different faces _edge_faces[:, 0]_ and _edge_faces[:, 1]_, which make the normal mistakenly computed. 

Looking forward to hearing from you!

Best,
Jia

**Comment by ranahanocka** [comment]
Hi @bertjiazheng 

Thanks a lot for the PR! :)

I started checking into this briefly. A short update:

Note that this function is not used to extract the input features to the network (extracting features happens in [extract_features](https://github.com/ranahanocka/MeshCNN/blob/71e88fc2c78418203f1dd9ab37ba390eb0c9d9d0/models/layers/mesh_prepare.py#L305) and uses different methods ([dihedral_angle](https://github.com/ranahanocka/MeshCNN/blob/71e88fc2c78418203f1dd9ab37ba390eb0c9d9d0/models/layers/mesh_prepare.py#L320), [symmetric_opposite_angles](https://github.com/ranahanocka/MeshCNN/blob/71e88fc2c78418203f1dd9ab37ba390eb0c9d9d0/models/layers/mesh_prepare.py#L328) and [symmetric_ratios](https://github.com/ranahanocka/MeshCNN/blob/71e88fc2c78418203f1dd9ab37ba390eb0c9d9d0/models/layers/mesh_prepare.py#L340) ).

So, **_the angles_from_faces function is only used to decide which edges to flip_**. The idea is that we tried to avoid flipping edges at sharp corners since it distorts the mesh. I remember we had some issues / noticed some odd behavior with this, but I thought we fixed them.

Anyway, I am going to take a look now at exporting some different edge flipped meshes and see if I can remember what is going on.

**Comment by bertjiazheng** [comment]
Hi @ranahanocka 

Yes, the _angles_from_faces_ only affect the edge flipping operation. 

The vertices of _edge_a_ (or _edge_b_) are from two different faces _edge_faces[:, 0]_ and _edge_faces[:, 1]_, and _normals[0]_ and _normals[1]_ are exactly the same. So the _dot_ only has two different results:
- if _edge_a_ and _edge_b_ are parallel, the normal of the face will be zero vector, the dot product of _normals[0]_ and _normals[1]_ results in zero, and _angles_ will be 90 deg; 
- else, the dot product of the _normals[0]_ and _normals[1]_ is always 1. The _angles_ will be 180 deg. 

Best,
Jia

**Comment by ranahanocka** [comment]
Hi @bertjiazheng ,

Nice catch - indeed this is a bug. Thanks for the PR :+1: 

Here is how an augmented mesh looked when applying edge flips (before):
image
and now with the fix:
image

**Pull request merged**
